/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'Data'
 * message type.
 */

public class Data extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 5;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 10;

    /** Create a new Data of size 5. */
    public Data() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new Data of the given data_length. */
    public Data(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new Data with the given data_length
     * and base offset.
     */
    public Data(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new Data using the given byte array
     * as backing store.
     */
    public Data(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new Data using the given byte array
     * as backing store, with the given base offset.
     */
    public Data(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new Data using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public Data(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new Data embedded in the given message
     * at the given base offset.
     */
    public Data(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new Data embedded in the given message
     * at the given base offset and length.
     */
    public Data(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <Data> \n";
      try {
        s += "  [rssi=0x"+Long.toHexString(get_rssi())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [car_id=0x"+Long.toHexString(get_car_id())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [node_id=0x"+Long.toHexString(get_node_id())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [direction=0x"+Long.toHexString(get_direction())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: rssi
    //   Field type: short, unsigned
    //   Offset (bits): 0
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'rssi' is signed (false).
     */
    public static boolean isSigned_rssi() {
        return false;
    }

    /**
     * Return whether the field 'rssi' is an array (false).
     */
    public static boolean isArray_rssi() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'rssi'
     */
    public static int offset_rssi() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'rssi'
     */
    public static int offsetBits_rssi() {
        return 0;
    }

    /**
     * Return the value (as a short) of the field 'rssi'
     */
    public short get_rssi() {
        return (short)getSIntBEElement(offsetBits_rssi(), 16);
    }

    /**
     * Set the value of the field 'rssi'
     */
    public void set_rssi(short value) {
        setSIntBEElement(offsetBits_rssi(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'rssi'
     */
    public static int size_rssi() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'rssi'
     */
    public static int sizeBits_rssi() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: car_id
    //   Field type: short, unsigned
    //   Offset (bits): 16
    //   Size (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'car_id' is signed (false).
     */
    public static boolean isSigned_car_id() {
        return false;
    }

    /**
     * Return whether the field 'car_id' is an array (false).
     */
    public static boolean isArray_car_id() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'car_id'
     */
    public static int offset_car_id() {
        return (16 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'car_id'
     */
    public static int offsetBits_car_id() {
        return 16;
    }

    /**
     * Return the value (as a short) of the field 'car_id'
     */
    public short get_car_id() {
        return (short)getUIntBEElement(offsetBits_car_id(), 8);
    }

    /**
     * Set the value of the field 'car_id'
     */
    public void set_car_id(short value) {
        setUIntBEElement(offsetBits_car_id(), 8, value);
    }

    /**
     * Return the size, in bytes, of the field 'car_id'
     */
    public static int size_car_id() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of the field 'car_id'
     */
    public static int sizeBits_car_id() {
        return 8;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: node_id
    //   Field type: short, unsigned
    //   Offset (bits): 24
    //   Size (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'node_id' is signed (false).
     */
    public static boolean isSigned_node_id() {
        return false;
    }

    /**
     * Return whether the field 'node_id' is an array (false).
     */
    public static boolean isArray_node_id() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'node_id'
     */
    public static int offset_node_id() {
        return (24 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'node_id'
     */
    public static int offsetBits_node_id() {
        return 24;
    }

    /**
     * Return the value (as a short) of the field 'node_id'
     */
    public short get_node_id() {
        return (short)getUIntBEElement(offsetBits_node_id(), 8);
    }

    /**
     * Set the value of the field 'node_id'
     */
    public void set_node_id(short value) {
        setUIntBEElement(offsetBits_node_id(), 8, value);
    }

    /**
     * Return the size, in bytes, of the field 'node_id'
     */
    public static int size_node_id() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of the field 'node_id'
     */
    public static int sizeBits_node_id() {
        return 8;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: direction
    //   Field type: short, unsigned
    //   Offset (bits): 32
    //   Size (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'direction' is signed (false).
     */
    public static boolean isSigned_direction() {
        return false;
    }

    /**
     * Return whether the field 'direction' is an array (false).
     */
    public static boolean isArray_direction() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'direction'
     */
    public static int offset_direction() {
        return (32 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'direction'
     */
    public static int offsetBits_direction() {
        return 32;
    }

    /**
     * Return the value (as a short) of the field 'direction'
     */
    public short get_direction() {
        return (short)getUIntBEElement(offsetBits_direction(), 8);
    }

    /**
     * Set the value of the field 'direction'
     */
    public void set_direction(short value) {
        setUIntBEElement(offsetBits_direction(), 8, value);
    }

    /**
     * Return the size, in bytes, of the field 'direction'
     */
    public static int size_direction() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of the field 'direction'
     */
    public static int sizeBits_direction() {
        return 8;
    }

}
